# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RTDS York
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Real-Time and Distributed Systems research group is concerned with fundamental
  and applied research into the development and analysis of systems where the distributed
  nature of the computation, the need for communication and coordination, and/or the
  timeliness of the system’s actions are of critical importance to the overall
  functionality and to the end-users.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rtsyork.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rtsyork
github_username:  RTSYork

# Build settings
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# Custom CSS
sass:
  style: compressed
  sass_dir: assets/css
plugins:
  - jekyll-feed
  - jekyll-remote-theme
nav_enabled: true

# External navigation links
#nav_external_links:
#  - title: Just the Docs on GitHub
#    url: https://github.com/just-the-docs/just-the-docs
#    hide_icon: false # set to true to hide the external link icon - defaults to false
#    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
